# Generated by Django 3.0.8 on 2020-08-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_point'),
        ('app', '0005_auto_20200813_1733'),
    ]

    operations = [
    ]
